In [1]:
#1.Arrays
import numpy

def arrays(arr):
    np_array=numpy.array(arr,float)
    return np_array[::-1]
    
    # complete this function
    # use numpy.array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
#2.Shape and Reshape
import numpy as np
n = input().strip().split(' ')
n1=np.array(n,int)
print(n1.reshape(3,3))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#3Transpose and Flatten
import numpy as np
N=input().split()
n,m=int(N[0]),int(N[1])
l=[input().split() for i in range(n)]
arr=np.array(l,dtype=int)
print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
#4.Concatenate
import numpy as np
n,m,p=[int(i) for i in input().split()]
arr1=np.array([input().split() for i in range(n)],int)
arr2=np.array([input().split() for j in range(m)],int)
print(np.concatenate((arr1,arr2),axis=0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [5]:
#5.Zeros and Ones

import numpy as np
n=tuple(map(int,input().split()))
print(np.zeros(n,int))
print(np.ones(n,int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [2]:
#6.Eye and Identity
import numpy as np
N=input().split()
n,m=int(N[0]),int(N[1])
np.set_printoptions(sign=" ")
print(np.eye(n,m))

4 4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [3]:
#7.Array Mathematics
import numpy as np
n,m=map(int, input().split())
A=np.array([input().split() for i in range(n)],dtype=int)
B=np.array([input().split() for i in range(n)],dtype=int)
print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [4]:
#8.Floor, Ceil and Rin

import numpy as np
n=np.array(input().split(),dtype=float)
np.set_printoptions(sign=" ")
f=np.floor(n)
c=np.ceil(n)
r=np.rint(n)
print(f)
print(c)
print(r)


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [5]:
#9.Sum and Prod
import numpy as np
n,m=map(int,input().split())
arr=np.array([input().split() for i in range(n)],dtype=int)
sum=np.sum(arr,axis=0)
product=np.product(sum,axis=0)
print(product)


2 2
1 4
2 5
27


In [6]:
#10.Min and Max
import numpy as np
n,m=list(map(int,input().split()))
arr= np.array([input().split() for i in range(n)],dtype=int)
minaxis=np.min(arr,axis=1)
print(max(minaxis))

4 2
2 5
3 7
1 3
4 0
3


In [5]:
#11.Mean, Var, and Std

import numpy as np


n,m=list(map(int,input().split()))
list1=[]
for i in range(n):
    l=list(map(int,input().split()))
    list1.append(l)
arr=np.array(list1)

print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
output=np.std(arr)
print(output.round(12))



2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


In [1]:
#12.Dot and Cross
import numpy as np
n=int(input())
a=np.array([input().split() for i in range(n)], dtype=int)
b=np.array([input().split() for i in range(n)], dtype=int)

print(a.dot(b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [2]:
#13.Inner and Outer

import numpy as np
a=np.array(input().split(),int)
b=np.array(input().split(),int)
print(np.inner(a,b))
print(np.outer(a,b))


0 1
2 3
3
[[0 0]
 [2 3]]


In [3]:
#14.Polynomials
import numpy as np
arr=np.array(input().split(),dtype=float)
print(np.polyval(arr,int(input())))

1.1 2 3
0
3.0


In [4]:
#15.Linear Algebra
import numpy as np
n=int(input())
arr=np.array([input().split() for i in range(n)],dtype=float)
output=np.linalg.det(arr)
print(output.round(2))

2
1.1 1.1
1.1 1.1
0.0
